- op: replace
  path: /spec/template/spec/containers/0/env/9
  value:
    name: KUMA_MULTIZONE_ZONE_GLOBAL_ADDRESS
    value: grpcs://100.100.100.100:5685
- op: replace
  path: /spec/template/spec/containers/0/env/10
  value:
    name: KUMA_MULTIZONE_ZONE_NAME
    value: mini
