apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mini--kuma-metrics
  namespace: argocd
spec:
  project: mini
  source:
    repoURL: 'https://github.com/amanibhavam/spiral-mini'
    path: kuma-metrics
    targetRevision: master
  destination:
    name: mini
    namespace: kuma-metrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
